import functools


class Kasiski:
    '''
    Uses Kasiski's examinstation to discover the key length for a vigenere encoded message
    Think the max might be set at 8 unsure and should be reviesd if this accours
    '''
    def __init__(self, cipher_text):
        cipher_text = cipher_text.replace(' ', '')
        self.original_cipher_text = cipher_text
        self.cipher_text = self.original_cipher_text

        self.multiples_list = self.factors()
        if not self.multiples_list:
            self.multiples_list = [x for x in range(0, 15, 1)]

    def output(self):
        '''
        Returns the calculated multiples
        '''
        return self.multiples_list

    def factors(self):
            '''
            Gets the factors of the length of the cipher text
            :return:
            '''

            n = len(self.cipher_text)
            return(list(set(functools.reduce(list.__add__, ([i, n//i] for i in range(1, int(n**0.5) + 1) if n % i == 0)))))


if __name__ == '__main__':
    cypher_text = '''CVJTNAFENMCDMKBXFSTKLHGSOJWHOFUISFYFBEXEINFIMAYSSDYYIJNPWTOKFRHWVWTZFXH
LUYUMSGVDURBWBIVXFAFMYFYXPIGBHWIFHHOJBEXAUNFIYLJWDKNHGAOVBHHGVINAULZFOF
UQCVFBYNFTYGMMSVGXCFZFOKQATUIFUFERQTEWZFOKMWOJYLNZBKSHOEBPNAYTFKNXLBVU
AXCXUYYKYTFRHRCFUYCLUKTVGUFQBESWYSSWLBYFEFZVUWTRLLNGIZGBMSZKBTNTSLNNMD
PMYMIUBVMTLOBJHHFWTJNAUFIZMBZLIVHMBSUWLBYFEUYFUFENBRVJVKOLLGTVUZUAOJNVU
WTRLMBATZMFSSOJQXLFPKNAULJCIOYVDRYLUJMVMLVMUKBTNAMFPXXJPDYFIJFYUWSGVIUM
BWSTUXMSSNYKYDJMCGASOUXBYSMCMEUNFJNAUFUYUMWSFJUKQWSVXXUVUFFBPWBCFYL
WFDYGUKDRYLUJMFPXXEFZQXYHGFLACEBJBXQSTWIKNMORNXCJFAIBWWBKCMUKIVQTMNBC
CTHLJYIGIMSYCFVMURMAYOBJUFVAUZINMATCYPBANKBXLWJJNXUJTWIKBATCIOYBPPZHLZJJZ
HLLVEYAIFPLLYIJIZMOUDPLLTHVEVUMBXPIBBMSNSCMCGONBHCKIVLXMGCRMXNZBKQHODESY
TVGOUGTHAGRHRMHFREYIJIZGAUNFZIYZWOUYWQZPZMAYJFJIKOVFKBTNOPLFWHGUSYTLGN
RHBZSOPMIYSLWIKBANYUOYAPWZXHVFUQAIATYYKYKPMCEYLIRNPCDMEIMFGWVBBMUPLHML
QJWUGSKQVUDZGSYCFBSWVCHZXFEXXXAQROLYXPIUKYHMPNAYFOFHXBSWVCHZXFEXXXAIR
PXXGOVHHGGSVNHWSFJUKNZBESHOKIRFEXGUFVKOLVJNAYIVVMMCGOFZACKEVUMBATVHKID
MVXBHLIVWTJAUFFACKHCIKSFPKYQNWOLUMYVXYYKYAOYYPUKXFLMBQOFLACKPWZXHUFJYG
ZGSTYWZGSNBBWZIVMNZXFIYWXWBKBAYJFTIFYKIZMUIVZDINLFFUVRGSSBUGNGOPQAILIFOZ
BZFYUWHGIRHWCFIZMWYSUYMAUDMIYVYAWVNAYTFEYYCLPWBBMVZZHZUHMRWXCFUYYVIEN
FHPYSMKBTMOIZWAIXZFOLBSMCHHNOJKBMBATZXXJSSKNAULBJCLFWXDSUYKUCIOYJGFLMBW
HFIWIXSFGXCZBMYMBWTRGXXSHXYKZGSDSLYDGNBXHAUJBTFDQCYTMWNPWHOFUISMIFFVXF
SVFRNA'''
    cypher_text = 'WJHZR DIAKZ TMCYS OMLVY HISNF BNZRP' \
                  'OESFJ RVLWL MIPOA LJAKD SQWLH KYSCN' \
                  'RMHPB OQNQQ MNBXC CACJN BOVVT LAUWJ' \
                  'RNISI FFBJO WZWIV NCWQM AUEEX TNOMR' \
                   'JIIYH ISNWD Y'

    # cypher_text = 'JVJAHVMDQIUGCJDASTDPHHMPQHYDPQYCAECPWFDSKFJPJLVJEVPRREVHXDHVFGCJDASTDDVAPCTBP'
    Kasiski(cypher_text)
