# Decodes a running cipher
from packages.pad import Decode
from packages.analyse import NthMessageQuag
import itertools
import multiprocessing
import time

class Quag:
    def __init__(self, cipher_text, degree):
        self.cipher_text = cipher_text
        alpha = [x for x in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ']
        # self.keys = itertools.product(alpha, repeat=degree)
        self.degree = degree


    def analyse(self):
        NthMessageQuag(self.cipher_text, self.degree)

    def start_single(self):
        # print(cipher_text)
        decode = Decode(self.cipher_text)
        plain_text = decode.quag('HELLO', 'DERP', 'A')
        print(plain_text)
        # self.analyse()

    def start(self):
        ''' MultiCore '''
        q = multiprocessing.Queue(maxsize=50)
        jobs = []

        # Create workers
        for i in range(0, multiprocessing.cpu_count(), 1):
            p = multiprocessing.Process(target=self.worker, args=(q,))
            p.start()
            jobs.append(p)

        # Feed items into the queue
        for each_item in self.keys:
            q.put(each_item)

    def worker(self, q):
        while True:
            if q.empty():
                time.sleep(1)
            try:
                pass
            except:
                break
        return

if __name__ == '__main__':
    cipher_text = open('cipher_3_text.txt', 'r').read()
    cipher_text = ''.join([x for x in cipher_text if x.isalpha()])
    test_text = ''.join([x for x in '''
    RDAJR TQCXS GPQTF ONWNP SWRDD OQCME PSDYG PLKBU FEPNR DBEZB VCCOG NJOOT
     CRRND RWMFE SNAGQ YOEBJ SAOWC FCPXS JMBCR ZGIQC SAOYC SGADR GEZBC MCPPM
     JHOPB WXEZE EMHEX CBYBV FBGOS EPXSD DFJTO OHTOZ VBPNI BGRDC PDHRQ YRBBV
     CRFMR PORJE PNXKB EZBAO QOXZI WNOZE IMORO YJSOM PUXAM BBEJS FFASF FFARD
     ROQHC OFRQB OZCRB ORKWZ DCQZS AOVQT IDATF RCOBM FTOSS DQFQH XUJTR NAQHV
     ONOZS OQHMY NMDRG SCBFU CDHES DFOMB QTSAO DAIQN LFORD UFMTP HZSKP CAGOZ
     SCLAD SGTAW LMDRF HAWQF BHFFO PPJRT EPJJN EDORN CJTPE COECN RZXAQ YASTO
     DXUVQ BTEHR QYVEP NSDGG VKGLR GEOBC XZIJH VGBNO VBIMQ NQDSG XEJBF HASOC
     UKTMN DJPGE LDQBD FJROO TRUVI KGPBB DFJPA MNTGO QBTMJ VORZE BZACF PNHGL
     JSNPR GRFRB UPBDG OHIEF RTEPS KQZVK GLCCU MQPOO OCOHZ DUONT ZZCWN OVTQO
     OBEPS BFPJH OBTKC YAOGV AEPHD YFLDV XZIYQ FQTID ATQZU KUMCD ELGNX ECJOE
     OKTET RODCD VEAOG VMBFH AJOEF UFECN OCRWN ODROC APOPS DVTAO UMQSJ VSAPO
     NJGVF MOEZK FECRX MRDVE ZBFMS YCMRD VVRSH MRSQP NYJPX KWMSE TPBCV CCNRZ
     CCUMQ JOZSC OYDOJ LCSDF JTOQJ TGMQE BSMBR ZQKWL SDVTS AOQDT UOASB EBKZM
     SAREJ EFXAH VOQAX DDHUC ASFEA COAZD BMNUA QARGO UBEVH YGLAE TRCUB EZEGM
     RTNPS AOLDS GORPO PLWXE ZEAPF AXZAF OTCRO CAETL JOWPN EWMNT OEFKN PUBFO
     MBOIO BEVAO TMZEB SBKBU SAODA TLAAS QTFUF ECNOC RAQHA VOCSA XDFEP NVEFU
     CKBUS DSMDC XESCO SJIVM QBBEJ SCMNT QGARA VNUGM RWXEZ TNVRJ HJVBP NFEPN
     ZKAYQ SAVSA GCXKB USDWM SAXDS VFMSG QZNBT EAHGO SAOSJ JXEDC SOWPE OOBEN
     XSQLA GQFBH EMFBX GAECV FTHCA OQNTG ZLAWR DIBGE JOWRB BRCBY VCTSG CDTOS
     EYGLA WNOBB QCGBR NDOUD SEEEA HSNDN XZINO TCRBO SFOVN JRQBB GOGDA JKDSA
     QDCMQ CLLCW XHDSH DACOD RBGRV AREAV OCBKZ MJSRV GKIMG BRNSW XEZTN VRFOT
     CRODC KGCJB UYXFO DSOQE SDGPL BXEOB EDCOR NBYSF SBIMN THPBC LVZEU ECEFX
     ZKAVH WORCU PSEDQ XDSOC UKTMS BTLSD GLAAQ YAETO TRGMR YTPBC GOIBG LJSGG
     VDEXJ OWRCR EMFTP JTOVO QTHZD TONXD HCEDQ XJOWR DCOZG EEHDS FLCWX ZIEBP
     OPQVN TAMNT UPXSQ FSTNP SSJLA ONMGR QAOBU EZKFO NNOSC OGQCT NMQSO ZGKBU
     DJQSG EAZSB TLNKT VDOSM FEHDA KPNEB UMDHS JSAOZ JNRZG TIVRT NMCOP JSAXZ
     IKNPU BPMHT RCAYQ FQBRN BYWOJ OWECN RXANO HDKGT CRREA GNVJO FEDOG NXION
     SFRSJ NOPNK IMZBR CGBIM QYTOM PPPJO GVNTN MEDQX DSGOV ALAAD CNAHQ ZSWRZ
     STQHD KGTCR REAGN QTTGL JSQZA MXZGD VUCTG OMBXY JOAJM KUDRD NONBF EBYXR
     DOGMU BBVME WVNBN OVKGY TSGTA BPECU GEARG LCSOH CRUDR DXDOD ZMVKG LMYFF
     OBEGJ SQCVA QDDKU EZBLS RBOVH WORCU PSIBG DCNOO NBQFS BRCBK OCEUG HAGQF
     BHBEO RQYJS OPNYG LJOWD CKPMS NEDMK GLLOQ HDOUL AWRDO ROSJG GPECL ZCTIM
     QYNPO PLHJT NYXEB DVBEP STNPS PQVNT XEDCA ORTFO TOUMG CXXAA ODSEE EAHGO
     FRLPN HJMNT XZSDN OVAOL DSBOH EAVBY PMHTR ZGOQT QKOZG SGLDT TOMBI VRKGE
     ZKFHD SRTSB EVDSZ MGKVE ZBEMV EFPNY QZAKB LJSSF JCUVN JGLDT AVIAG QAESN
     ATQLA CCYDO XTACG EAREV ECODC KGOCM XETPQ ZMYFM BIGOD SZYQS AVSAX TJGQF
     BHCPX EIVRK GLACX GAHXZ DSAPB CTVSY QGARV CCNJL AROVV EFZCT IMQYV PQTQS
     QKIMZ BJPRE PVSTP MRAQR LBUVV EFHJC PVNJG OGDGL JSSFS SQFNH OSSAR ZLIHN
     JWRDV KPNJO WECGQ YADHE DOULA CCLJN CMQSQ ZDCPJ RDXLA EUOUB EUATG OSAOC
     ASXSA OTMDO UYABG LJNJV SAXZR BTONH FVZEU EZBTP ECOCT OBVNJ RUDKB DJNCN
     AKBAT TTLDO WMDOU MUBBQ QDHUZ TNVME FVMPP VHKOS QBAOS BVOQA XDRBG ECPSO
     WTQPU DXSSA XDORQ QBBAV NTNMH UGFQB GLDTF HZBBL ASGPQ TOSFR LVNJN MIDOD
     JOGOZ DJLAA RDNTR RSURN BYFAC MOZCR EMDCP JJOGM QETEA HJVSA RZXDB MHDEJ
     AEEDZ BWPUB AMDAH UDOUE CCUYA AQHSA RZLIH NZBJP RTNPS KTPMB QFSEB SZBPA
     AHNVM EBSSD PSMBN OVSQC QYNMV EFTCR SMJOW DCNOP NBRCB KOCCO XDDKU VSWRD
     NDCCC FPMME BSJWR DZECA XTQLA CCPNH GLDTJ PRKGV BBVEV BOXRC REARA JRUCM
     QVXDC RTOMB FECNL SASZP NHRDL SAMJI XRCUP SFDAM RPOPL WXEZA OCHDE PEKGP
     EDHED ORRFD HZSIQ CMRFY JTNET RBDCU GLASO ZSTNM FESNA GQYOE BJDCO ESBEO
     TTPVN KBUZD JEZEB XHUPL AWRDH DELAC CVNJN VMWXE ZAXDJ SFFAE BSZDJ VSROP
     BCLYD HOPND PSMEB LDPCJ DJRVN IQCCO TMJOR GARLN COWEJ NOEZB PMSTO CVEFT
     QEAMG EBSOU GONDH CHRQZ SBBEQ EBRAT QCATR VBKWF ASFEZ BAOQE POHTN VRSGO
     QYXDN DAPST OCZDJ ZDSGJ RDAMC OOVRT QJCUQ GARGL APNON BFOMB GVMBF EZBLC
     AOQED CJPXS REARE VECOA ARFON EBSKU FEIDX ZITNC CUWLD CQEJS GVBCG LJOZP
     EDHEM RFYJT NOFGR DJDBP BCLHZ BBVIB GEZDF MNEFE XGHDS DAMQS RZGKG YDMOD
     MBVMA CRNJT GNAFO ESBEP NYJPX TNPNM FTCRE MDHXZ ILHDS TNOTJ NEJHF LDROL
     CWGLJ SQZAG RNBGN PNJOS MYQFS CQOLD BNJIO
    ''' if x.isalpha()])
    quag = Quag(test_text, 9)
    # running.start()
    quag.start_single()
